#!/bin/bash

export SCRIPTDIR=$(dirname $(realpath $BASH_SOURCE))

STDCXX=17
SYSTEMC_INCLUDE=$SYSTEMC_HOME/include
SYSTEMC_LIBRARY=$SYSTEMC_HOME/lib-mingw64
# SYSTEMC_LIBRARY=$SYSTEMC_HOME/lib-linux64

SRCNAME=hello

SRCFILE=$SCRIPTDIR/$SRCNAME.cpp
EXEFILE=$SCRIPTDIR/$SRCNAME.exe

export LD_LIBRARY_PATH=$SYSTEMC_LIBRARY:$LD_LIBRARY_PATH

if [ -f "$EXEFILE" ]; then
    rm -f $EXEFILE
fi

g++ --std=gnu++$STDCXX -I$SYSTEMC_INCLUDE -L$SYSTEMC_LIBRARY -lsystemc $SRCFILE -o $EXEFILE
$EXEFILE
