#!/bin/bash

export SCRIPTDIR=$(dirname $(realpath $BASH_SOURCE))

STDCXX=17

SYSTEMC_INCLUDE=$SYSTEMC_HOME/include
SYSTEMC_LIBRARY=$SYSTEMC_HOME/lib-mingw64
# SYSTEMC_LIBRARY=$SYSTEMC_HOME/lib-linux64

CCI_CONFIG=$CCI_HOME/src
CCI_LIBRARY=$CCI_HOME/lib

SRCNAME=hello

SRCFILE=$SCRIPTDIR/$SRCNAME.cpp
EXEFILE=$SCRIPTDIR/$SRCNAME.exe

export LD_LIBRARY_PATH=$SYSTEMC_LIBRARY:$CCI_LIBRARY:$LD_LIBRARY_PATH

if [ -f "$EXEFILE" ]; then
    rm -f $EXEFILE
fi

g++ --std=gnu++$STDCXX -I$SYSTEMC_INCLUDE -I$CCI_CONFIG -L$SYSTEMC_LIBRARY -L$CCI_LIBRARY -lsystemc -lcciapi $SRCFILE -o $EXEFILE
$EXEFILE
